### ISSUE TITLE
Change signature to either size_t or unsigned long long

### ISSUE THREAD

**Issue by mkannwischer** [pqov/pqov#20]
https://github.com/pqov/pqov/blob/b688edea9258ec19a9596b1738e397b282bf3a99/src/sign.c#L67

Casting an `unsigned long long` to `unsigned` is maybe not the best idea...

**Comment by devillegna** [comment]
agree. unsigned might restrict the size of message to be 4TB. 
which one is better between size_t or unsigned long long?

**Comment by mkannwischer** [comment]
Resolved by #21
